name: automatically publish package to pub.dev

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+*'

jobs:
  publish_to_pub_dev:
    permissions:
      id-token: write # need this for OIDC  

    uses: dart-lang/setup-dart/.github/workflows/publish.yml@v1