name: automatically publish package to pub.dev

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+*'

jobs:
  publish_to_pub_dev:
    permissions:
      id-token: write # need this for OIDC  

    # uses: dart-lang/setup-dart/.github/workflows/publish.yml@v1

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dart-lang/setup-dart@v1
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.7.7'
          channel: 'stable'
      - name: check flutter version
        run: flutter --version
      - name: Install dependencies
        run: flutter pub get
      - name: Publish
        run: dart pub publish --force